kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ tpl .Values.resource.default.namespace . }}
  name: {{ tpl .Values.resource.np.name . }}
spec:
  podSelector:
    matchLabels:
      app: {{ tpl .Values.resource.default.name . }}
  ingress:
  - ports:
    - port: {{ .Values.resource.port.port }}
      protocol: {{ .Values.resource.port.protocol }}
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
  policyTypes:
  - Egress
  - Ingress
