kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ include "resource.default.namespace" . }}
  name: {{ include "resource.networkPolicy.name" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "resource.default.name" . }}
  ingress:
  - ports:
    - port: {{ .Values.resource.service.port }}
      protocol: {{ .Values.resource.service.protocol }}
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
    - ipBlock:
        cidr: 172.16.0.0/12
    - ipBlock:
        cidr: 192.168.0.0/16
  policyTypes:
  - Egress
  - Ingress
