apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    app: {{ include "resource.default.name" . }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: {{ include "resource.default.name" . }}
    port: {{ .Values.resource.service.port }}
    targetPort: {{ .Values.resource.service.port }}
  selector:
    app: {{ include "resource.default.name" . }} 
