apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    app: {{ tpl .Values.resource.default.name  . }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: {{ tpl .Values.resource.default.name  . }}
    port: {{ tpl .Values.resource.port.port . }}
    targetPort: {{ tpl .Values.resource.port.port . }}
  selector:
    app: {{ tpl .Values.resource.default.name  . }} 
