apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: {{ .Values.name }}
    port: 9410
    targetPort: 9410
  selector:
    app: {{ .Values.name }} 
