version: 2.1

orbs:
  architect: giantswarm/architect@6.4.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-vault-exporter
          binary: vault-exporter
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: "architect"
          name: push-to-registries
          requires:
            - go-build-vault-exporter
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-to-playground-app-catalog
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "vault-exporter"
          # Make sure docker image is successfully built.
          requires:
            - push-to-registries
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
