image:
  registry: "quay.io"
  repository: "giantswarm/vault-exporter"
  tag: "[[ .Version ]]"
pod:
  user:
    id: 1000
  group:
    id: 1000
resource:
  service:
    port: "9410"
    protocol: "TCP"
