image:
  name: "giantswarm/vault-exporter"
  tag: "[[ .Version ]]"

registry:
  domain: gsoci.azurecr.io

pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

vaultAddress: ""

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
    - ALL

global:
  podSecurityStandards:
    enforced: false
