image:
  repository: "giantswarm/vault-exporter"
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io
pod:
  user:
    id: 1000
  group:
    id: 1000
resource:
  service:
    port: "9410"
    protocol: "TCP"
